### ISSUE TITLE
Error Loggin into Gmail

### ISSUE THREAD

**Issue by ebnerjoh** [AbhyudayaSharma/MailPrinter#6]
Hi,

I am getting an error when logging into Gmail:

```
MailPrinter is now running...
Checking for emails
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/mailprinter/MailPrinter-master/mailprinter/__main__.py", line 23, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 693, in run
    ret = self.job_func()
  File "/usr/local/lib/python3.9/dist-packages/mailprinter-0.0.0-py3.9.egg/mailprinter/core/reader.py", line 27, in read_email
  File "/usr/lib/python3.9/imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'
```

Credentials are Correct!

**Comment by AbhyudayaSharma** [comment]
@ebnerjoh I think you would need to use an [app password](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by ebnerjoh** [comment]
@AbhyudayaSharma 

Yes, I learned that the Authentication is now based on OAuth2 on most of the Mail services.

On Gmail you cannot use App Passwords anymore (except paid version).

But luckily I have a M365 NGO Subscription. I created a mailbox, activated MFA and added an APP Password.

But I am getting still an error:

```
MailPrinter is now running...
Checking for emails
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/mailprinter/MailPrinter-master/mailprinter/__main__.py", line 23, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.9/dist-packages/schedule-1.2.0-py3.9.egg/schedule/__init__.py", line 693, in run
    ret = self.job_func()
  File "/usr/local/lib/python3.9/dist-packages/mailprinter-0.0.0-py3.9.egg/mailprinter/core/reader.py", line 27, in read_email
  File "/usr/lib/python3.9/imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.error: b'LOGIN failed.'
```

Need to somehow check if the APP PASSWORD is working...

**Comment by ebnerjoh** [comment]
Ok, I was not able to get it working with M365. Althouh I have enabled MFA and created an APP PASSWORD, I got the "Login failed".

I have now created a mailaddress on gmx.net, enabled also MFA and APP PASSWORD and with that its working.

I have no idea why the APP Password on M365 E2 is not accepted.

**Comment by ebnerjoh** [comment]
Ok, typically MS. APP PASSWORD can be still configured, but not supported anymore. Only modern authentication.
